use_frameworks!

platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AdParticipesCumCepis_Example' do
  pod 'AdParticipesCumCepis', :path => '../'

  pod 'Stencil', '~> 0.14'
end

target 'ActionExtension' do
  pod 'AdParticipesCumCepisExtension', :path => '../'
end
