use_frameworks!

platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AdParticipesCumCepis_Example' do
  pod 'AdParticipesCumCepis', :path => '../'

  pod 'Stencil', '~> 0.14'

  target 'AdParticipesCumCepis_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.1'
  end
end

target 'ActionExtension' do
  pod 'AdParticipesCumCepisExtension', :path => '../'
end

# Fix Xcode 14 code signing issues with bundles.
# See https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-1249151085
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
