//
//  FileManager+Utils.swift
//  AdParticipesCumCepis
//
//  Created by Benjamin Erhart on 12.10.21.
//

import Foundation

public extension FileManager {

    var cacheDir: URL? {
        urls(for: .cachesDirectory, in: .userDomainMask).first
    }

    var docsDir: URL? {
        urls(for: .documentDirectory, in: .userDomainMask).first
    }

    /**
     Store data in <appdir>/Library/Caches/tor (Library/Caches/ is for things that can persist between
     launches -- which we'd like so we keep descriptors & etc -- but don't need to be backed up because
     they can be regenerated by the app)
     */
    var torDir: URL? {
        guard let url = cacheDir?.appendingPathComponent("tor", isDirectory: true) else {
            return nil
        }

        // Create tor data directory if it does not yet exist.
        try? createSecureDirIfNotExists(at: url)

        return url
    }

    func createSecureDirIfNotExists(at url: URL) throws {
        // Try to remove it, if it is *not* a directory.
        if fileExists(at: url) {
            if !((try? url.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory ?? false) {
                try removeItem(at: url)
            }
        }

        // Try to create it, and all its intermediate directories, if it doesn't
        // exist. Create with secure permissions.
        if !fileExists(at: url) {
            try createDirectory(
                at: url, withIntermediateDirectories: true,
                attributes: [.posixPermissions: NSNumber(value: 0o700)])
        }
    }

    func fileExists(at url: URL) -> Bool {
        return url.isFileURL && fileExists(atPath: url.path)
    }

    func size(of url: URL) -> Int64? {
        guard let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize else {
            return nil
        }

        return Int64(size)
    }

    func lastModified(of url: URL) -> Date? {
        return try? url.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate
    }

    func contentsOfDirectory(at url: URL?) -> [URL] {
        guard let url = url else {
            return []
        }

        return (try? contentsOfDirectory(
            at: url, includingPropertiesForKeys: nil,
            options: .skipsHiddenFiles)) ?? []
    }

    func shareDir(of appGroupId: String?) -> URL? {
        guard let appGroupId = appGroupId else {
            return nil
        }

        return containerURL(forSecurityApplicationGroupIdentifier: appGroupId)
    }

    func fileExists(at url: URL?) -> Bool {
        guard let url = url else {
            return false
        }

        return fileExists(at: url)
    }

    func createDirectory(at url: URL?) throws {
        guard let url = url else {
            return
        }

        try createDirectory(at: url, withIntermediateDirectories: true)
    }

    func moveItem(at srcURL: URL?, to dstURL: URL?) throws {
        guard let srcURL = srcURL, let dstURL = dstURL else {
            return
        }

        try moveItem(at: srcURL, to: dstURL)
    }

    func linkItem(at srcURL: URL?, to dstURL: URL?) throws {
        guard let srcURL = srcURL, let dstURL = dstURL else {
            return
        }

        try linkItem(at: srcURL, to: dstURL)
    }
}
